config/routes.rb
Rails.application.routes.draw do
  resources :shindans

  resource :shindans

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :title
  validates :answer, presence: true
end

app/models/shindan.rb
class Shindan < ActiveRecord::Base
  validates :title, presence: true
  has_many :answers, :dependent => :destroy

  after_update :save_answers

  def new_answer_attributes=(answer_attributes)
    answer_attributes.each do |attributes|
      answers.build attributes
    end
  end

  def existing_answer_attributes=(answer_attributes)
    answers.reject(&:new_record?).each do |answer|
      attributes = answer_attributes[answer.id.to_s]
      if attributes
        answer.attributes = attributes
      else
        answers.delete(answer)
      end
    end
  end

  def save_answers
    answer.each do |answer|
      answer.save(false)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shindans_controller.rb
class ShindansController < ApplicationController
  before_action :set_shindan, only: [:show, :edit, :update, :destroy]

  # GET /shindans
  # GET /shindans.json
  def index
    @shindans = Shindan.order('id DESC').limit(10).all
  end

  # GET /shindans/1
  # GET /shindans/1.json
  def show
  end

  # GET /shindans/new
  def new
    @shindan = Shindan.new
  end

  # GET /shindans/1/edit
  def edit
    @shindan = Shindan.find params[:id]
  end

  # POST /shindans
  # POST /shindans.json
  def create
    # @shindan = Shindan.new(shindan_params)
    #
    # respond_to do |format|
    #   if @shindan.save
    #     format.html { redirect_to @shindan, notice: 'Shindan was successfully created.' }
    #     format.json { render :show, status: :created, location: @shindan }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @shindan.errors, status: :unprocessable_entity }
    #   end
    # end
    render plain params[:shindan].inspect
  end

  # PATCH/PUT /shindans/1
  # PATCH/PUT /shindans/1.json
  def update
    respond_to do |format|
      if @shindan.update(shindan_params)
        format.html { redirect_to @shindan, notice: 'Shindan was successfully updated.' }
        format.json { render :show, status: :ok, location: @shindan }
      else
        format.html { render :edit }
        format.json { render json: @shindan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shindans/1
  # DELETE /shindans/1.json
  def destroy
    @shindan.destroy
    respond_to do |format|
      format.html { redirect_to shindans_url, notice: 'Shindan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shindan
      @shindan = Shindan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shindan_params
      params.require(:shindan).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shindans_helper.rb
module ShindansHelper
  def fields_for_answer(answer, &block)
    prefix = answer.new_record? ? 'new' : 'existing'
    fields_for "shindan[#{prefix}_task_attributes][]", task, &block
  end

  def add_answer_link(name)
    link_to name do |page|
      page.insert_html :bottom, :answers, :partial => 'answer', :object => Answer.new
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OpenShindan
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/shindans/_answer.html.haml
%div{class:'answer'}
  = fields_for_answer answer do |answer_form|
  %p
    Answer = answer_form.text_field :name
    = link_to "remove", "javascript:void(0);", id="remove_answer"
  = @answer = answer
  = error_messages_for :answer

app/views/shindans/_answers.html.haml
%div{id: "answers"}
  Answers
  = render :partial => "answer", :collection => @shindan.answers
  = add_answer_link "Add a link"

app/views/shindans/_form.html.haml
= form_for @shindan do |f|
  - if @shindan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shindan.errors.count, "error")} prohibited this shindan from being saved:"
      %ul
        - @shindan.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/shindans/edit.html.haml
%h1 Editing shindan

= render 'form'

= link_to 'Show', @shindan
\|
= link_to 'Back', shindans_path

app/views/shindans/index.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OpenShindan - Shindans
  %body
    %h1 Questions
    =link_to new_shindan_path do
      New

app/views/shindans/new.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OpenShindan - Shindan
  %body
    %h1 New Question
    = form_for @shindan, :url => {:controller => 'shindans', :action => 'index'} do |form|
      = form.label :title
      = form.text_field :title
      %br
      = render :partial => 'answers', :locals => {:form => form}
      %br
      = form.submit "Create Question"

app/views/shindans/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @shindan.title

= link_to 'Edit', edit_shindan_path(@shindan)
\|
= link_to 'Back', shindans_path